Repository CaZaIt/CaZaIt-Android-Private, pull requests merged in 2023-03, with the labels that each got.

#5 [Feat] #1 add sign in activity
  app/src/main/res/drawable-hdpi/login_logo.9.png
  app/src/main/res/drawable-mdpi/login_logo.9.png
  app/src/main/res/drawable-xhdpi/login_logo.9.png
  app/src/main/res/drawable-xxhdpi/login_logo.9.png
  app/src/main/res/drawable-xxxhdpi/login_logo.9.png
  app/src/main/res/drawable/login_logo.png
  app/src/main/res/drawable/roundcorner_dologin.xml
  app/src/main/res/drawable/roundcorner_name_pass.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: design

#7 [Fix] #1 비밀번호 입력 타입 변경
  app/src/main/res/layout/activity_sign_in.xml
Labels: design

#10 [Add] CafeListFragment
  app/build.gradle
  app/src/androidTest/java/org/cafelist/CafeListFragment.kt
  app/src/androidTest/java/org/cafelist/CafeListViewModel.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/cazait/ui/component/MainActivity.kt
  app/src/main/java/org/cazait/ui/component/MainViewModel.kt
  app/src/main/java/org/cazait/ui/component/cafelist/CafeListFragment.kt
  app/src/main/java/org/cazait/ui/component/cafelist/CafeListViewModel.kt
  app/src/main/res/drawable/round_corner_do_login.xml
  app/src/main/res/drawable/round_corner_name_pass.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/fragment_cafe_list.xml
  app/src/main/res/menu/bnv_menu.xml
  app/src/main/res/menu/menu_main.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: design

#16 [Add] Android detekt
  app/build.gradle
  app/src/androidTest/java/org/cafelist/CafeListFragment.kt
  app/src/androidTest/java/org/cafelist/CafeListViewModel.kt
  app/src/androidTest/java/org/cazait/ExampleInstrumentedTest.kt
  app/src/main/java/org/cazait/CazaitApplication.kt
  app/src/main/java/org/cazait/di/AppModule.kt
  app/src/main/java/org/cazait/di/DataModule.kt
  app/src/main/java/org/cazait/ui/base/BaseActivity.kt
  app/src/main/java/org/cazait/ui/base/BaseFragment.kt
  app/src/main/java/org/cazait/ui/base/BaseViewModel.kt
  app/src/main/java/org/cazait/ui/component/MainActivity.kt
  app/src/main/java/org/cazait/ui/component/MainViewModel.kt
  app/src/main/java/org/cazait/ui/component/cafelist/CafeListFragment.kt
  app/src/main/java/org/cazait/ui/component/cafelist/CafeListViewModel.kt
  app/src/main/java/org/cazait/ui/component/signin/SignInActivity.kt
  app/src/main/java/org/cazait/ui/component/signin/SignInViewModel.kt
  app/src/main/java/org/cazait/ui/component/signup/SignUpActivity.kt
  app/src/main/java/org/cazait/ui/component/signup/SignUpViewModel.kt
  app/src/main/java/org/cazait/utils/SingleEvent.kt
  app/src/main/java/org/cazait/utils/ViewExt.kt
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/dimens.xml
  app/src/test/java/org/cazait/ExampleUnitTest.kt
  build.gradle
  detekt.yml
Labels: review needed

#17 [Add] Apple SD Gothic
  app/src/main/res/font/applesdgothic.ttf
  app/src/main/res/font/applesdgothicneob00.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/fragment_cafe_list.xml
Labels: design

#18 [Feat] #13 - add dependency injection
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/cazait/data/Resource.kt
  app/src/main/java/org/cazait/data/api/AuthService.kt
  app/src/main/java/org/cazait/data/api/UserService.kt
  app/src/main/java/org/cazait/data/error/Error.kt
  app/src/main/java/org/cazait/data/error/ErrorManager.kt
  app/src/main/java/org/cazait/data/error/ErrorUseCase.kt
  app/src/main/java/org/cazait/data/error/mapper/ErrorMapper.kt
  app/src/main/java/org/cazait/data/error/mapper/ErrorMapperSource.kt
  app/src/main/java/org/cazait/data/model/request/RefreshTokenReq.kt
  app/src/main/java/org/cazait/data/model/request/SignInReq.kt
  app/src/main/java/org/cazait/data/model/request/SignUpReq.kt
  app/src/main/java/org/cazait/data/model/response/IsEmailDupRes.kt
  app/src/main/java/org/cazait/data/model/response/IsNicknameDupRes.kt
  app/src/main/java/org/cazait/data/model/response/RefreshTokenRes.kt
  app/src/main/java/org/cazait/data/model/response/SignInRes.kt
  app/src/main/java/org/cazait/data/model/response/SignUpRes.kt
  app/src/main/java/org/cazait/data/remote/ServiceGenerator.kt
  app/src/main/java/org/cazait/data/remote/auth/AuthRemoteData.kt
  app/src/main/java/org/cazait/data/remote/auth/AuthRemoteDataSource.kt
  app/src/main/java/org/cazait/data/remote/user/UserRemoteData.kt
  app/src/main/java/org/cazait/data/remote/user/UserRemoteDataSource.kt
  app/src/main/java/org/cazait/data/repository/auth/AuthRepository.kt
  app/src/main/java/org/cazait/data/repository/auth/AuthRepositoryImpl.kt
  app/src/main/java/org/cazait/data/repository/users/UserRepository.kt
  app/src/main/java/org/cazait/data/repository/users/UserRepositoryImpl.kt
  app/src/main/java/org/cazait/di/AppModule.kt
  app/src/main/java/org/cazait/di/DataModule.kt
  app/src/main/java/org/cazait/network/Network.kt
  app/src/main/java/org/cazait/network/NetworkConnectivity.kt
  app/src/main/res/values/strings.xml
  build.gradle
Labels: invalid, review needed, testing needed, api
