Repository CaZaIt/CaZaIt-Android-Private, pull requests merged in 2023-05, with the labels that each got.

#46 [Feat] #44 - cafes load
  app/src/main/java/org/cazait/data/api/AuthService.kt
  app/src/main/java/org/cazait/data/api/CafeService.kt
  app/src/main/java/org/cazait/data/dto/request/CafeListReq.kt
  app/src/main/java/org/cazait/data/dto/request/RefreshTokenReq.kt
  app/src/main/java/org/cazait/data/dto/response/CafeListRes.kt
  app/src/main/java/org/cazait/data/dto/response/CafeOfCafeList.kt
  app/src/main/java/org/cazait/data/dto/response/RefreshTokenRes.kt
  app/src/main/java/org/cazait/data/mapper/CafeMapper.kt
  app/src/main/java/org/cazait/data/model/Cafe.kt
  app/src/main/java/org/cazait/data/model/MockData.kt
  app/src/main/java/org/cazait/data/model/mapper/CafeListResMapper.kt
  app/src/main/java/org/cazait/data/remote/auth/AuthRemoteData.kt
  app/src/main/java/org/cazait/data/remote/auth/AuthRemoteDataSource.kt
  app/src/main/java/org/cazait/data/remote/cafe/CafeListRemoteData.kt
  app/src/main/java/org/cazait/data/remote/cafe/CafeListRemoteDataSource.kt
  app/src/main/java/org/cazait/data/repository/cafe/CafeRepository.kt
  app/src/main/java/org/cazait/data/repository/cafe/CafeRepositoryImpl.kt
  app/src/main/java/org/cazait/ui/adapter/CafeListVerticalAdapter.kt
  app/src/main/java/org/cazait/ui/adapter/ItemDecoration.kt
  app/src/main/java/org/cazait/ui/component/cafeinfo/CafeInfoViewModel.kt
  app/src/main/java/org/cazait/ui/component/cafelist/CafeListFragment.kt
  app/src/main/java/org/cazait/ui/component/cafelist/CafeListViewModel.kt
  app/src/main/java/org/cazait/ui/component/map/CafeMapFragment.kt
  app/src/main/java/org/cazait/ui/component/map/MapViewModel.kt
  app/src/main/res/layout/item_cafe_with_landscape.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: review needed, api

#52 [Feat] #51 - 마이 페이지, 최근 본 매장, 더 보기
  app/src/main/java/org/cazait/ui/component/MainActivity.kt
  app/src/main/java/org/cazait/ui/component/mypage/MyPageFragment.kt
  app/src/main/java/org/cazait/ui/component/mypage/MyPageViewModel.kt
  app/src/main/res/drawable/home.xml
  app/src/main/res/drawable/ic_arrow_circle_right.xml
  app/src/main/res/drawable/ic_badge.xml
  app/src/main/res/drawable/ic_big_home.xml
  app/src/main/res/drawable/ic_credit_card.xml
  app/src/main/res/drawable/ic_headset_mic.xml
  app/src/main/res/drawable/ic_local_atm.xml
  app/src/main/res/drawable/ic_settings.xml
  app/src/main/res/drawable/ic_verified_user.xml
  app/src/main/res/drawable/rectangle_70.png
  app/src/main/res/drawable/rectangle_see_more.xml
  app/src/main/res/drawable/shadow_box.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_recently_cafe.xml
  app/src/main/res/layout/fragment_see_more.xml
  app/src/main/res/layout/item_recently_cafe.xml
  app/src/main/res/values/styles.xml
  gradle/wrapper/gradle-wrapper.properties
Labels: in progress, review needed

#58 [Refact] #55 - 마이페이지, 최근 본 매장, 더 보기 수정
  app/src/main/res/drawable/btn_ic_recently.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_recently_cafe.xml
  app/src/main/res/layout/fragment_see_more.xml
  app/src/main/res/layout/item_recently_cafe.xml
Labels: in progress, review needed

#60 [Fix] #59 - fix_recently_icon
  app/src/main/res/layout/item_recently_cafe.xml
Labels: bug

#62 [Refactor] #53 - CafeListFragment, ViewModel, Resource(font)
  app/src/main/java/org/cazait/data/mapper/CafeMapper.kt
  app/src/main/java/org/cazait/ui/adapter/ItemDecoration.kt
  app/src/main/java/org/cazait/ui/component/cafelist/CafeListFragment.kt
  app/src/main/java/org/cazait/ui/component/cafelist/CafeListViewModel.kt
  app/src/main/res/font/_apple_sd_gothic_neo_eb.ttf
  app/src/main/res/font/_apple_sd_gothic_neo_h.ttf
  app/src/main/res/font/_apple_sd_gothic_neo_l.ttf
  app/src/main/res/font/_apple_sd_gothic_neo_m.ttf
  app/src/main/res/font/_apple_sd_gothic_neo_r.ttf
  app/src/main/res/font/_apple_sd_gothic_neo_sb.ttf
  app/src/main/res/font/apple_sd_gothic_neo_eb.xml
  app/src/main/res/font/apple_sd_gothic_neo_h.xml
  app/src/main/res/font/apple_sd_gothic_neo_l.xml
  app/src/main/res/font/apple_sd_gothic_neo_m.xml
  app/src/main/res/font/apple_sd_gothic_neo_r.xml
  app/src/main/res/font/apple_sd_gothic_neo_sb.xml
  app/src/main/res/layout/item_cafe_just_info.xml
  app/src/main/res/layout/item_cafe_with_landscape.xml
  app/src/main/res/layout/map_cafe_info_layout.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
Labels: review needed

#87 [Feat] #86 - Load data from RoomDB when not logged in
  app/src/main/java/org/cazait/data/repository/cafe/CafeRepositoryImpl.kt
  app/src/main/java/org/cazait/data/source/remote/cafe/CafeListRemoteData.kt
  app/src/main/java/org/cazait/domain/repository/CafeRepository.kt
  app/src/main/java/org/cazait/ui/base/BaseFragment.kt
  app/src/main/java/org/cazait/ui/component/cafelist/CafeListFragment.kt
  app/src/main/java/org/cazait/ui/component/cafelist/CafeListViewModel.kt
  app/src/main/java/org/cazait/ui/component/map/CafeMapFragment.kt
  app/src/main/res/layout/item_cafe_just_info.xml
Labels: review needed

#93 [Feat] #83 - edit review
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/cazait/ui/component/cafeinfo/detail/CafeInfoReviewFragment.kt
  app/src/main/java/org/cazait/ui/component/cafelist/CafeListFragment.kt
  app/src/main/java/org/cazait/ui/component/review/ReviewEditActivity.kt
  app/src/main/java/org/cazait/ui/component/review/ReviewEditViewModel.kt
  app/src/main/res/drawable/ic_baseline_edit_24.xml
  app/src/main/res/drawable/ic_star_empty.xml
  app/src/main/res/drawable/ic_star_fill.xml
  app/src/main/res/drawable/layerlist_rating_star.xml
  app/src/main/res/drawable/rectangle_black_r20.xml
  app/src/main/res/drawable/rectangle_white_r25.xml
  app/src/main/res/drawable/rectangle_white_r50.xml
  app/src/main/res/drawable/selector_rating.xml
  app/src/main/res/drawable/selector_rating_blank.xml
  app/src/main/res/drawable/selector_rating_fill.xml
  app/src/main/res/drawable/star_empty.png
  app/src/main/res/drawable/star_fill.png
  app/src/main/res/layout/activity_cafe_info.xml
  app/src/main/res/layout/activity_review_edit.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/fragment_cafe_info_menu.xml
  app/src/main/res/layout/fragment_cafe_info_review.xml
  app/src/main/res/layout/item_cafe_info_menu.xml
  app/src/main/res/layout/item_recently_cafe.xml
  app/src/main/res/layout/layout_page_top.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  core/data/src/main/java/org/bmsk/data/repository/CafeRepository.kt
  core/data/src/main/java/org/bmsk/data/repository/CafeRepositoryImpl.kt
  core/data/src/main/java/org/bmsk/data/repository/UserRepository.kt
  core/data/src/main/java/org/bmsk/data/repository/UserRepositoryImpl.kt
  core/network/src/main/java/org/cazait/network/api/CafeService.kt
  core/network/src/main/java/org/cazait/network/datasource/CafeInfoRemoteData.kt
  core/network/src/main/java/org/cazait/network/datasource/CafeInfoRemoteDataSource.kt
  core/network/src/main/java/org/cazait/network/model/dto/request/CafeReviewReq.kt
  core/network/src/main/java/org/cazait/network/model/dto/response/CafeReviewRes.kt
Labels: ready for merger
